# Web properties
server.port=8080

#env file
spring.config.import=optional:file:.env[.properties]

#spring profile
spring.profiles.active=${APP_ENV:prod}

# PostgreSQL Database Configuration
spring.datasource.url=${PG_URL}
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Initialize schema
spring.sql.init.mode=always
# spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:schema.sql

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

#JWT settings
jwt.token.issuer=ITIntegration-Robin-Ghys
jwt.secret-key=${JWT_SECRET}
jwt.token.lifetime=${JWT_EXPIRE}